python: "3.10"
odoo:
  custom:
    - /Users/mjavint/Workspaces/Aside/Templates/vsc-odoo/OCA/helpdesk
  server: /Users/mjavint/Repos/Odoo/odoo/odoo.17.0
  # enterprise: <enterprise_repo>
repos:
  - /Users/mjavint/Workspaces/Aside/Templates/vsc-odoo/OCA/helpdesk
